A destructor should never throw an exception.[3]